// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:105da7b7-24f7-49ce-a810-65457b9385bf",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4JmNoFpce",
    "aws_user_pools_web_client_id": "3f257efj8bpbitiu0vj3akjalf",
    "oauth": {}
};


export default awsmobile;
